/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BringToFrontPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var translations = {
  en: {
    language: "Language",
    languageDesc: "Display language",
    auto: "Auto",
    chinese: "\u4E2D\u6587",
    english: "English",
    keywords: "Keywords (optional)",
    keywordsDesc: "Leave empty to bring to front on any modal/notice when Obsidian is in the background. Add comma-separated keywords to trigger when any one of them appears.",
    watchScope: "Watch scope",
    watchScopeDesc: "Which elements to monitor",
    scopeModal: "Modals",
    scopeNotice: "Notices",
    scopeBoth: "Modals & Notices",
    scopeCustom: "Custom selector",
    customSelector: "CSS Selector",
    customSelectorDesc: 'Custom CSS selector (e.g. .modal-container, [data-type="my-plugin"])',
    focusInterval: "Focus cooldown (seconds)",
    focusIntervalDesc: "Minimum time between focus actions. Prevents repeated focus stealing. 0 = no cooldown",
    debugMode: "Debug mode",
    debugModeDesc: "Log matching details to console (Ctrl+Shift+I)",
    matchDetected: "Match detected, bringing to front",
    windowFocused: "Window already focused, skipping",
    cooldownActive: "Cooldown active, skipping",
    guide: "Quick Start Guide",
    guideKeywords: "By default (no keywords), Obsidian is brought to front whenever a modal or notice appears while it is in the background. Add comma-separated keywords to only trigger when any keyword appears in the element text.",
    guideScope: 'Watch scope: "Modals" watches popup dialogs, "Notices" watches toast messages, "Both" watches everything. Use "Custom" for advanced CSS selectors.',
    guideExamples: "Examples",
    guideEx1: 'Reminder popup \u2192 keywords "Snooze, Done", scope "Modals"',
    guideEx2: 'Error alerts \u2192 keywords "error, failed", scope "Notices"',
    guideEx3: 'All modals & notices \u2192 leave keywords empty, scope "Both" (default)',
    guideTip: "Tip: To find a CSS selector \u2014 open DevTools (Ctrl+Shift+I), click the inspect icon (top-left of DevTools panel), click the target element, then use the class names shown in the Elements panel (e.g. .my-plugin-modal)."
  },
  zh: {
    language: "\u8BED\u8A00",
    languageDesc: "\u663E\u793A\u8BED\u8A00",
    auto: "\u81EA\u52A8",
    chinese: "\u4E2D\u6587",
    english: "English",
    keywords: "\u5173\u952E\u8BCD\uFF08\u53EF\u9009\uFF09",
    keywordsDesc: "\u7559\u7A7A\u5373\u53EF\uFF1A\u540E\u53F0\u51FA\u73B0\u5F39\u7A97\u6216\u901A\u77E5\u65F6\u81EA\u52A8\u7F6E\u9876\u3002\u586B\u5199\u9017\u53F7\u5206\u9694\u7684\u5173\u952E\u8BCD\uFF0C\u51FA\u73B0\u4EFB\u4E00\u5373\u89E6\u53D1\u3002",
    watchScope: "\u76D1\u542C\u8303\u56F4",
    watchScopeDesc: "\u76D1\u542C\u54EA\u7C7B\u5143\u7D20",
    scopeModal: "\u5F39\u7A97",
    scopeNotice: "\u901A\u77E5",
    scopeBoth: "\u5F39\u7A97\u548C\u901A\u77E5",
    scopeCustom: "\u81EA\u5B9A\u4E49\u9009\u62E9\u5668",
    customSelector: "CSS \u9009\u62E9\u5668",
    customSelectorDesc: '\u81EA\u5B9A\u4E49 CSS \u9009\u62E9\u5668\uFF08\u5982 .modal-container\u3001[data-type="my-plugin"]\uFF09',
    focusInterval: "\u805A\u7126\u51B7\u5374\uFF08\u79D2\uFF09",
    focusIntervalDesc: "\u4E24\u6B21\u7F6E\u9876\u4E4B\u95F4\u7684\u6700\u5C0F\u95F4\u9694\uFF0C\u9632\u6B62\u53CD\u590D\u62A2\u7126\u30020 = \u4E0D\u9650\u5236",
    debugMode: "\u8C03\u8BD5\u6A21\u5F0F",
    debugModeDesc: "\u5728\u63A7\u5236\u53F0\uFF08Ctrl+Shift+I\uFF09\u8F93\u51FA\u5339\u914D\u65E5\u5FD7",
    matchDetected: "\u68C0\u6D4B\u5230\u5339\u914D\uFF0C\u6B63\u5728\u7F6E\u9876",
    windowFocused: "\u7A97\u53E3\u5DF2\u5728\u524D\u53F0\uFF0C\u8DF3\u8FC7",
    cooldownActive: "\u51B7\u5374\u4E2D\uFF0C\u8DF3\u8FC7",
    guide: "\u5165\u95E8\u6307\u5357",
    guideKeywords: "\u9ED8\u8BA4\u65E0\u9700\u914D\u7F6E\uFF1A\u540E\u53F0\u51FA\u73B0\u5F39\u7A97\u6216\u901A\u77E5\u65F6\u81EA\u52A8\u7F6E\u9876\u3002\u5982\u9700\u8FC7\u6EE4\uFF0C\u586B\u5165\u9017\u53F7\u5206\u9694\u7684\u5173\u952E\u8BCD\uFF0C\u51FA\u73B0\u4EFB\u4E00\u5173\u952E\u8BCD\u5373\u89E6\u53D1\u3002",
    guideScope: "\u76D1\u542C\u8303\u56F4\uFF1A\u300C\u5F39\u7A97\u300D\u76D1\u542C\u5BF9\u8BDD\u6846\u5F39\u7A97\uFF0C\u300C\u901A\u77E5\u300D\u76D1\u542C\u53F3\u4E0A\u89D2\u63D0\u793A\u6D88\u606F\uFF0C\u300C\u5F39\u7A97\u548C\u901A\u77E5\u300D\u540C\u65F6\u76D1\u542C\u4E24\u8005\u3002\u9700\u8981\u66F4\u7075\u6D3B\u7684\u5339\u914D\u8BF7\u9009\u300C\u81EA\u5B9A\u4E49\u300D\u8F93\u5165 CSS \u9009\u62E9\u5668\u3002",
    guideExamples: "\u914D\u7F6E\u793A\u4F8B",
    guideEx1: '\u63D0\u9192\u5F39\u7A97 \u2192 \u5173\u952E\u8BCD "Snooze, Done"\uFF0C\u8303\u56F4\u300C\u5F39\u7A97\u300D',
    guideEx2: '\u9519\u8BEF\u63D0\u793A \u2192 \u5173\u952E\u8BCD "error, failed"\uFF0C\u8303\u56F4\u300C\u901A\u77E5\u300D',
    guideEx3: "\u6240\u6709\u5F39\u7A97\u548C\u901A\u77E5 \u2192 \u5173\u952E\u8BCD\u7559\u7A7A\uFF0C\u8303\u56F4\u300C\u5F39\u7A97\u548C\u901A\u77E5\u300D\uFF08\u9ED8\u8BA4\uFF09",
    guideTip: "\u63D0\u793A\uFF1A\u67E5\u627E CSS \u9009\u62E9\u5668\u2014\u2014\u6253\u5F00\u5F00\u53D1\u8005\u5DE5\u5177\uFF08Ctrl+Shift+I\uFF09\uFF0C\u70B9\u51FB\u5DE6\u4E0A\u89D2\u7684\u9009\u62E9\u5668\u56FE\u6807\uFF0C\u70B9\u51FB\u76EE\u6807\u5143\u7D20\uFF0C\u5728 Elements \u9762\u677F\u4E2D\u67E5\u770B class \u540D\u79F0\uFF08\u5982 .my-plugin-modal\uFF09\u3002"
  }
};
var SCOPE_SELECTORS = {
  modal: ".modal-container",
  notice: ".notice",
  both: ".modal-container, .notice"
};
var DEFAULT_SETTINGS = {
  keywords: "",
  watchScope: "both",
  customSelector: "",
  focusInterval: 5,
  language: "auto",
  debugMode: false
};
var BringToFrontPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.lastFocusTime = 0;
    this.observer = null;
    this.restartTimer = null;
    this.cachedKeywords = [];
  }
  debug(msg) {
    if (this.settings?.debugMode) console.debug(`[Bring to Front] ${msg}`);
  }
  async onload() {
    await this.loadSettings();
    this.updateTranslations();
    this.addSettingTab(new BringToFrontSettingTab(this.app, this));
    this.setupDetection();
    this.debug("Plugin loaded");
  }
  onunload() {
    this.cleanup();
  }
  cleanup() {
    this.observer?.disconnect();
    this.observer = null;
    if (this.restartTimer) window.clearTimeout(this.restartTimer);
    this.restartTimer = null;
  }
  // --- Detection ---
  getSelector() {
    if (this.settings.watchScope === "custom") {
      return this.settings.customSelector.trim() || SCOPE_SELECTORS.both;
    }
    return SCOPE_SELECTORS[this.settings.watchScope] || SCOPE_SELECTORS.both;
  }
  setupDetection() {
    const selector = this.getSelector();
    this.observer = new MutationObserver((mutations) => {
      for (const mutation of mutations) {
        for (let i = 0; i < mutation.addedNodes.length; i++) {
          const node = mutation.addedNodes[i];
          if (node instanceof HTMLElement) {
            this.checkNode(node, selector);
          }
        }
      }
    });
    this.observer.observe(document.body, { childList: true, subtree: true });
    this.checkExisting(selector);
  }
  checkNode(node, selector) {
    try {
      let target = null;
      if (node.matches(selector)) {
        target = node;
      } else {
        target = node.querySelector(selector);
      }
      if (target && this.matchesKeywords(target)) {
        this.handleMatch();
      }
    } catch {
    }
  }
  checkExisting(selector) {
    if (this.isWindowFocused()) return;
    try {
      const el = document.querySelector(selector);
      if (el && this.matchesKeywords(el)) {
        this.handleMatch();
      }
    } catch {
    }
  }
  updateKeywordCache() {
    this.cachedKeywords = this.settings.keywords.split(",").map((k) => k.trim().toLowerCase()).filter((k) => k.length > 0);
  }
  matchesKeywords(el) {
    if (this.cachedKeywords.length === 0) return true;
    const text = (el.textContent || "").toLowerCase();
    return this.cachedKeywords.some((kw) => text.includes(kw));
  }
  // --- Focus ---
  handleMatch() {
    if (this.isWindowFocused()) {
      this.debug(this.t("windowFocused"));
      return;
    }
    if (this.settings.focusInterval > 0) {
      const now = Date.now();
      if ((now - this.lastFocusTime) / 1e3 < this.settings.focusInterval) {
        this.debug(this.t("cooldownActive"));
        return;
      }
      this.lastFocusTime = now;
    }
    this.debug(this.t("matchDetected"));
    void this.bringToFront();
  }
  isWindowFocused() {
    const win = this.getElectronWindow();
    if (win) return win.isFocused();
    return document.hasFocus();
  }
  async bringToFront() {
    try {
      window.focus();
      const win = this.getElectronWindow();
      if (!win) return;
      if (win.isMinimized()) win.restore();
      if (!win.isVisible()) win.show();
      if (!win.isAlwaysOnTop()) {
        win.setAlwaysOnTop(true);
        await new Promise((r) => setTimeout(r, 200));
        win.setAlwaysOnTop(false);
      }
      win.focus();
    } catch (e) {
      console.error("[Bring to Front]", e);
    }
  }
  getElectronWindow() {
    try {
      const electronWindow = window;
      if (electronWindow.require) {
        try {
          const remote = electronWindow.require("@electron/remote");
          if (remote) return remote.getCurrentWindow();
        } catch {
        }
        const electron = electronWindow.require("electron");
        return electron?.remote?.getCurrentWindow() ?? null;
      }
    } catch {
    }
    return null;
  }
  // --- i18n ---
  updateTranslations() {
    const lang = this.getLanguage();
    this.t = (key) => translations[lang][key] || translations["en"][key] || key;
  }
  getLanguage() {
    if (this.settings.language === "zh") return "zh";
    if (this.settings.language === "en") return "en";
    const obsidianApp = this.app;
    const obsidianLang = obsidianApp.vault?.config?.language;
    const systemLang = navigator.language.toLowerCase();
    return obsidianLang?.includes("zh") || systemLang.includes("zh") ? "zh" : "en";
  }
  // --- Settings ---
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    this.updateKeywordCache();
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.updateTranslations();
    this.updateKeywordCache();
  }
  restartDetection() {
    if (this.restartTimer) window.clearTimeout(this.restartTimer);
    this.restartTimer = window.setTimeout(() => {
      this.restartTimer = null;
      this.cleanup();
      this.setupDetection();
    }, 300);
  }
};
var BringToFrontSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    const t = this.plugin.t.bind(this.plugin);
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName(t("language")).setDesc(t("languageDesc")).addDropdown((dd) => dd.addOption("auto", t("auto")).addOption("zh", t("chinese")).addOption("en", t("english")).setValue(this.plugin.settings.language).onChange(async (v) => {
      this.plugin.settings.language = v;
      await this.plugin.saveSettings();
      this.display();
    }));
    new import_obsidian.Setting(containerEl).setName(t("keywords")).setDesc(t("keywordsDesc")).addTextArea((ta) => {
      ta.setPlaceholder("Snooze, Done").setValue(this.plugin.settings.keywords).onChange(async (v) => {
        this.plugin.settings.keywords = v;
        await this.plugin.saveSettings();
        this.plugin.restartDetection();
      });
      ta.inputEl.rows = 2;
    });
    new import_obsidian.Setting(containerEl).setName(t("watchScope")).setDesc(t("watchScopeDesc")).addDropdown((dd) => dd.addOption("modal", t("scopeModal")).addOption("notice", t("scopeNotice")).addOption("both", t("scopeBoth")).addOption("custom", t("scopeCustom")).setValue(this.plugin.settings.watchScope).onChange(async (v) => {
      this.plugin.settings.watchScope = v;
      await this.plugin.saveSettings();
      this.plugin.restartDetection();
      this.display();
    }));
    if (this.plugin.settings.watchScope === "custom") {
      new import_obsidian.Setting(containerEl).setName(t("customSelector")).setDesc(t("customSelectorDesc")).addText((tx) => tx.setPlaceholder(".modal-container, .notice").setValue(this.plugin.settings.customSelector).onChange(async (v) => {
        this.plugin.settings.customSelector = v;
        await this.plugin.saveSettings();
        this.plugin.restartDetection();
      }));
    }
    new import_obsidian.Setting(containerEl).setName(t("focusInterval")).setDesc(t("focusIntervalDesc")).addText((tx) => {
      tx.setPlaceholder("5").setValue(String(this.plugin.settings.focusInterval)).onChange(async (v) => {
        const n = parseInt(v);
        if (!isNaN(n) && n >= 0) {
          this.plugin.settings.focusInterval = n;
          await this.plugin.saveSettings();
        }
      });
      tx.inputEl.type = "number";
      tx.inputEl.min = "0";
      tx.inputEl.step = "1";
    });
    new import_obsidian.Setting(containerEl).setName(t("debugMode")).setDesc(t("debugModeDesc")).addToggle((tg) => tg.setValue(this.plugin.settings.debugMode).onChange(async (v) => {
      this.plugin.settings.debugMode = v;
      await this.plugin.saveSettings();
    }));
    const guide = containerEl.createEl("details");
    guide.createEl("summary", { text: t("guide") });
    const gc = guide.createDiv();
    gc.createEl("p", { text: t("guideKeywords") });
    gc.createEl("p", { text: t("guideScope") });
    new import_obsidian.Setting(gc).setName(t("guideExamples")).setHeading();
    const ul = gc.createEl("ul");
    ul.createEl("li", { text: t("guideEx1") });
    ul.createEl("li", { text: t("guideEx2") });
    ul.createEl("li", { text: t("guideEx3") });
    gc.createEl("p", { text: t("guideTip") });
  }
};
